### ISSUE TITLE
Separate the Roadmap + user stories to their own document 📃

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/kindly#272]
### Prerequisites

- [x] I have checked the existing Issues for a duplicate of this ticket
- [x] I have checked the roadmap in the documentation and am convinced this Issue fits the plans for future releases
- [x] This Issue will help us achieve at least one of the existing User Stories for the product (directly or indirectly)

### Expected Behavior

The Roadmap and User Stories should be quick to find for anyone navigating our documentation and easier for us to edit in future, since these will need adapting with each new release.

### Current Behavior

Based on feedback we've gotten the roadmap can be difficult to spot as contributors are not necessarily expecting product info to be in the `CONTRIBUTING.md`

### Any other notes

We might just have a `PRODUCT_ROADMAP.md` and add it to the list of docs linked in the `README.md`

### Assignment

This issue is free for anyone to take
